YLP-699 Add CodeQL Analysis
mdblp/gatekeeper pull request #27
Opened 2021-06-15 12:26 UTC by ragedblp

2021-06-16 10:21 UTC, yvon-dblg requested changes

2021-06-16 10:21 UTC, yvon-dblg commented on CHANGELOG.md
> +- YLP-785 Bump some dependencies
Wrong changelog message

2021-06-21 09:05 UTC, ragedblp commented on CHANGELOG.md
> +- YLP-785 Bump some dependencies
Removed

2021-06-21 09:10 UTC, yvon-dblg approved these changes
LGTM

2021-06-21 09:10 UTC, merged